# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mmanuell <mmanuell@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/23 16:47:49 by mgalvez           #+#    #+#              #
#    Updated: 2025/05/14 18:16:00 by mmanuell         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all :
	@ make -C ./CPP00
	@ make -C ./CPP01
	@ make -C ./CPP02
	@ make -C ./CPP03
	@ make -C ./CPP04
	@ make -C ./CPP05
	@ make -C ./CPP06
	@ make -C ./CPP07
	@ make -C ./CPP08
	@ make -C ./CPP09

clean:
	@ make clean -C ./CPP00
	@ make clean -C ./CPP01
	@ make clean -C ./CPP02
	@ make clean -C ./CPP03
	@ make clean -C ./CPP04
	@ make clean -C ./CPP05
	@ make clean -C ./CPP06
	@ make clean -C ./CPP07
	@ make clean -C ./CPP08
	@ make clean -C ./CPP09

fclean:	clean
	@ make fclean -C ./CPP00
	@ make fclean -C ./CPP01
	@ make fclean -C ./CPP02
	@ make fclean -C ./CPP03
	@ make fclean -C ./CPP04
	@ make fclean -C ./CPP05
	@ make fclean -C ./CPP06
	@ make fclean -C ./CPP07
	@ make fclean -C ./CPP08
	@ make fclean -C ./CPP09

re:	fclean all

.PHONY: all clean fclean re
